export const SELECT_VALUE = "SELECT_VALUE";
export const USER_SELECTED_VALUES = "USER_SELECTED_VALUES";
export const USER_NARROWED_VALUES = "USER_NARROWED_VALUES";
export const USER_ENTERED_PROJECTS = "USER_ENTERED_PROJECTS";
