export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";
export const SUBMIT_PROJECT = "SUBMIT_PROJECT";

export const START_EDIT_PROJECT = "START_EDIT_PROJECT";
export const FINISH_EDIT_PROJECT = "FINISH_EDIT_PROJECT";
